### ISSUE TITLE
Post-processing (medication/allergen meta-annotations and lookups)

### ISSUE THREAD

**Issue by jenniferjiangkells** [uclh-criu/miade#48]
Converted as separate issue from #34
 
Updated algorithm design from 04/11/22

Require a number of lookup tables in post-processing:
data: https://github.com/uclh-criu/miade-datasets/

- [ ] meds: function to map VTM to default VMP with substance and dosage (MiADE_VTM_VMP_dose_lookup.csv)
- [ ] allergy: function to map native SNOMED to ELG SNOMED, causative agent lookup (MiADE_causative_agent_lookup.csv)
- [ ] substance lookup: MiADE_ingredients_lookup.csv 
- [ ] reaction: function to map SNOMED to set of common SNOMED concepts that are mapped to Epic (MiADE_med_allergy_reaction_lookup.csv)
- [ ] may need pre-processing of spaces between number and letters (i.e. 75mg vs 75 mg) for meds concepts

Also require change in processing how concept categories are assigned as all terms are now SNO; Categories are now Problem, Medication, Allergy, Reaction; changes required

- [x] Process meds/allergy meta-annotation when concepts are being assigned category
